In [10]:
import numpy as np

In [11]:
print(7)

7


In [12]:
a = np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
arr.sum(axis=0)

array([12, 15, 18])

In [17]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
arr.size

9

In [21]:
arr.sort

<function ndarray.sort>

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr.max

<function ndarray.max>

In [29]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])