In [68]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr.shape

(2, 3)

In [71]:
arr = arr.reshape(3,2)

In [72]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
arr.shape

(3, 2)

#Multidimension Array into Single Dimension Array


In [74]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr = arr.reshape(-1)

In [76]:
arr.shape

(9,)

#Transpose Array

In [77]:
arr = np.array([[1,2,3,45],[54,4,5,6],[7,18,8,9]])
arr

array([[ 1,  2,  3, 45],
       [54,  4,  5,  6],
       [ 7, 18,  8,  9]])

In [78]:
arr = arr.T

In [79]:
arr

array([[ 1, 54,  7],
       [ 2,  4, 18],
       [ 3,  5,  8],
       [45,  6,  9]])

#Array Multiplication

In [81]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[3,4],[5,6]])

In [83]:
arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
arr3 = np.matmul(arr1,arr2)

In [86]:
arr3

array([[22, 28],
       [49, 64]])

In [87]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [88]:
np.dot(arr,5)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])