In [8]:
import numpy as np

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr + arr1

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [12]:
arr * arr1

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [13]:
np.sqrt(arr1)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [14]:
arr1.sum()

np.int64(450)

In [15]:
arr.max()

np.int64(9)

In [16]:
arr1.max()

np.int64(90)

In [17]:
arr1.min()

np.int64(10)

In [18]:
np.count_nonzero(arr1)

9