In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [11]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr.ndim

2

In [15]:
arr.shape

(3, 5)

In [16]:
arr.size

15

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr.itemsize

8

In [22]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
arr[:,3]

array([ 4,  9, 14])

In [23]:
arr[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
arr[::-1]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [26]:
arr1 = np.zeros((3,4))

In [27]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr2 = np.ones((3,4))

In [29]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr = np.random.rand(3,4)

In [31]:
arr

array([[0.64738012, 0.97961901, 0.66203677, 0.03008769],
       [0.08962669, 0.2546795 , 0.58491415, 0.22799616],
       [0.87625848, 0.88434846, 0.57856779, 0.08005508]])

In [32]:
arr = np.random.rand(10)

In [33]:
arr

array([0.58449326, 0.44715856, 0.13834385, 0.45943787, 0.06555009,
       0.7433011 , 0.20457038, 0.66372316, 0.70786817, 0.48547704])

In [34]:
arr = np.random.randint(1,20,20)

In [35]:
arr

array([12,  6,  3, 14, 14,  5,  2,  2, 10, 17, 13, 17,  7, 14,  3, 12, 14,
       19, 14,  7], dtype=int32)

In [37]:
arr = np.array([[1,2,3],[4,5,6]])

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr[0]

array([1, 2, 3])

In [40]:
arr[1]

array([4, 5, 6])

In [43]:
print(arr[0,2])

3


In [44]:
arr[arr>3]

array([4, 5, 6])

In [45]:
arr[arr>5]

array([6])

In [46]:
arr>3

array([[False, False, False],
       [ True,  True,  True]])